# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# compile CXX with /usr/bin/c++
CXX_DEFINES = -DOPENFHE1788_SOURCE_COMMIT=\"28bab40431eebc85d72521c6d9dc840ecd675cd7\"

CXX_INCLUDES = -I/home/runner/work/20231788./20231788./tests -I/home/runner/work/20231788./20231788./include -isystem /home/runner/work/20231788./20231788./.ci/openfhe-install-34265676284-1/include/openfhe -isystem /home/runner/work/20231788./20231788./.ci/openfhe-install-34265676284-1/include/openfhe/third-party/include -isystem /home/runner/work/20231788./20231788./.ci/openfhe-install-34265676284-1/include/openfhe/core -isystem /home/runner/work/20231788./20231788./.ci/openfhe-install-34265676284-1/include/openfhe/pke -isystem /home/runner/work/20231788./20231788./.ci/openfhe-install-34265676284-1/include/openfhe/binfhe

CXX_FLAGS =   -Wall -Werror -DOPENFHE_VERSION=1.5.0 -Wno-parentheses -O3 -DMATHBACKEND=4 -fopenmp -g -std=c++17 -Werror

